version: "2"
run:
  tests: true
linters:
  enable:
    - asciicheck
    - bidichk
    - copyloopvar
    - errorlint
    - gocyclo
    - goheader
    - gosec
    - misspell
    - nilerr
    - revive
    - staticcheck
    - tparallel
    - unconvert
    - unparam
  disable:
    - prealloc
    - unused
  settings:
    gocyclo:
      min-complexity: 11
    govet:
      disable:
        - fieldalignment
      enable-all: true
    misspell:
      locale: US
    revive:
      rules:
        - name: dot-imports
          disabled: true
    staticcheck:
      dot-import-whitelist:
        - github.com/onsi/ginkgo/v2
        - github.com/onsi/gomega
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - goheader
        path: zz_(.+)\.go
      - path: (.+)\.go$
        text: declaration of "(err|ctx)" shadows declaration at
    paths:
      - tools
      - website
      - hack
      - charts
      - designs
      - third_party$
      - builtin$
      - examples$
issues:
  fix: true
formatters:
  enable:
    - gci
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - localmodule
    goimports:
      local-prefixes:
        - github.com/cloudpilot-ai/karpenter-provider-gcp
  exclusions:
    generated: lax
    paths:
      - tools
      - website
      - hack
      - charts
      - designs
      - third_party$
      - builtin$
      - examples$
