apiVersion: karpenter.k8s.gcp/v1alpha1
kind: GCENodeClass
metadata:
  name: default-example
spec:
  serviceAccount: <fill-me>
  subnetworkSelectorTerms:
    - name: karpenter-provider-gcp
  imageSelectorTerms:
    - alias: ContainerOptimizedOS
  tags:
    env: dev
