apiVersion: karpenter.k8s.gcp/v1alpha1
kind: GCENodeClass
metadata:
  name: default-example
spec:
  serviceAccount: "" # fill me
  imageSelectorTerms:
    - alias: ContainerOptimizedOS@v117-18613.263.14
    # - alias: ContainerOptimizedOS@latest
  tags:
    env: dev
